// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace HeartDiseaseDetection
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Timestamp (GPS - UTC)")]
            public string Timestamp__GPS___UTC_ { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Aux1FuelIndexAIi_input")]
            public float Aux1FuelIndexAIi_input { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Aux2FuelIndexAIi_input")]
            public float Aux2FuelIndexAIi_input { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"Aux3FuelIndexAIi_input")]
            public float Aux3FuelIndexAIi_input { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"MEFuelIndexAIi_input")]
            public float MEFuelIndexAIi_input { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"BoilerAux1lFuelIndexAIi_input")]
            public float BoilerAux1lFuelIndexAIi_input { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"SB9_2EGPT1AIi")]
            public float SB9_2EGPT1AIi { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"SB9_2EGPT2AIi")]
            public float SB9_2EGPT2AIi { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"SB9_2EGPT3AIi")]
            public float SB9_2EGPT3AIi { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"SB9_2EGPT4AIi")]
            public float SB9_2EGPT4AIi { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"SB9_2EGPT5AIi")]
            public float SB9_2EGPT5AIi { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"NETWAOutletTT31AIi")]
            public float NETWAOutletTT31AIi { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"SB3_1PT2_1AIi")]
            public float SB3_1PT2_1AIi { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"SB3_1FT2_1AIi")]
            public float SB3_1FT2_1AIi { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"SB3_1LT5_1AIi")]
            public float SB3_1LT5_1AIi { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"SB3_1LT6_1AIi")]
            public float SB3_1LT6_1AIi { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"SB3_1PDT1_1AIi")]
            public float SB3_1PDT1_1AIi { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"SB3_1TT5_1AIi")]
            public float SB3_1TT5_1AIi { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"SB3_1TT6_1AIi")]
            public float SB3_1TT6_1AIi { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"SB3_1TT7_1AIi")]
            public float SB3_1TT7_1AIi { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"PF2_1a_FrqCurrRaw")]
            public float PF2_1a_FrqCurrRaw { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"PF2_1a_Eprw")]
            public float PF2_1a_Eprw { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"PF2_1a_Spd")]
            public float PF2_1a_Spd { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"PF2_1b_FrqCurrRaw")]
            public float PF2_1b_FrqCurrRaw { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"PF2_1b_Eprw")]
            public float PF2_1b_Eprw { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"PF2_1b_Spd")]
            public float PF2_1b_Spd { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"NETEGARatioAIi")]
            public float NETEGARatioAIi { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"NETWAOutletPAHT31AIi")]
            public float NETWAOutletPAHT31AIi { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"NETWAOutletpHT31AIi")]
            public float NETWAOutletpHT31AIi { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"Scrub_EGACO2Coni")]
            public float Scrub_EGACO2Coni { get; set; }

            [LoadColumn(30)]
            [ColumnName(@"Scrub_EGASO2Coni")]
            public float Scrub_EGASO2Coni { get; set; }

            [LoadColumn(31)]
            [ColumnName(@"NETWAInletTUET30AIi")]
            public float NETWAInletTUET30AIi { get; set; }

            [LoadColumn(32)]
            [ColumnName(@"NETWAInletpHT30AIi")]
            public float NETWAInletpHT30AIi { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Timestamp (GPS - UTC)")]
            public float[] Timestamp__GPS___UTC_ { get; set; }

            [ColumnName(@"Aux1FuelIndexAIi_input")]
            public float Aux1FuelIndexAIi_input { get; set; }

            [ColumnName(@"Aux2FuelIndexAIi_input")]
            public float Aux2FuelIndexAIi_input { get; set; }

            [ColumnName(@"Aux3FuelIndexAIi_input")]
            public float Aux3FuelIndexAIi_input { get; set; }

            [ColumnName(@"MEFuelIndexAIi_input")]
            public float MEFuelIndexAIi_input { get; set; }

            [ColumnName(@"BoilerAux1lFuelIndexAIi_input")]
            public float BoilerAux1lFuelIndexAIi_input { get; set; }

            [ColumnName(@"SB9_2EGPT1AIi")]
            public float SB9_2EGPT1AIi { get; set; }

            [ColumnName(@"SB9_2EGPT2AIi")]
            public float SB9_2EGPT2AIi { get; set; }

            [ColumnName(@"SB9_2EGPT3AIi")]
            public float SB9_2EGPT3AIi { get; set; }

            [ColumnName(@"SB9_2EGPT4AIi")]
            public float SB9_2EGPT4AIi { get; set; }

            [ColumnName(@"SB9_2EGPT5AIi")]
            public float SB9_2EGPT5AIi { get; set; }

            [ColumnName(@"NETWAOutletTT31AIi")]
            public float NETWAOutletTT31AIi { get; set; }

            [ColumnName(@"SB3_1PT2_1AIi")]
            public float SB3_1PT2_1AIi { get; set; }

            [ColumnName(@"SB3_1FT2_1AIi")]
            public float SB3_1FT2_1AIi { get; set; }

            [ColumnName(@"SB3_1LT5_1AIi")]
            public float SB3_1LT5_1AIi { get; set; }

            [ColumnName(@"SB3_1LT6_1AIi")]
            public float SB3_1LT6_1AIi { get; set; }

            [ColumnName(@"SB3_1PDT1_1AIi")]
            public float SB3_1PDT1_1AIi { get; set; }

            [ColumnName(@"SB3_1TT5_1AIi")]
            public float SB3_1TT5_1AIi { get; set; }

            [ColumnName(@"SB3_1TT6_1AIi")]
            public float SB3_1TT6_1AIi { get; set; }

            [ColumnName(@"SB3_1TT7_1AIi")]
            public float SB3_1TT7_1AIi { get; set; }

            [ColumnName(@"PF2_1a_FrqCurrRaw")]
            public float PF2_1a_FrqCurrRaw { get; set; }

            [ColumnName(@"PF2_1a_Eprw")]
            public float PF2_1a_Eprw { get; set; }

            [ColumnName(@"PF2_1a_Spd")]
            public float PF2_1a_Spd { get; set; }

            [ColumnName(@"PF2_1b_FrqCurrRaw")]
            public float PF2_1b_FrqCurrRaw { get; set; }

            [ColumnName(@"PF2_1b_Eprw")]
            public float PF2_1b_Eprw { get; set; }

            [ColumnName(@"PF2_1b_Spd")]
            public float PF2_1b_Spd { get; set; }

            [ColumnName(@"NETEGARatioAIi")]
            public float NETEGARatioAIi { get; set; }

            [ColumnName(@"NETWAOutletPAHT31AIi")]
            public float NETWAOutletPAHT31AIi { get; set; }

            [ColumnName(@"NETWAOutletpHT31AIi")]
            public float NETWAOutletpHT31AIi { get; set; }

            [ColumnName(@"Scrub_EGACO2Coni")]
            public float Scrub_EGACO2Coni { get; set; }

            [ColumnName(@"Scrub_EGASO2Coni")]
            public float Scrub_EGASO2Coni { get; set; }

            [ColumnName(@"NETWAInletTUET30AIi")]
            public float NETWAInletTUET30AIi { get; set; }

            [ColumnName(@"NETWAInletpHT30AIi")]
            public float NETWAInletpHT30AIi { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
